# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    labels:
      - "Platform/Rust"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    labels:
      - "Platform/Docker"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    labels:
      - "Platform/GitHubActions"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    labels:
      - "Platform/NodeJS"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    versioning-strategy: "widen"
